### ISSUE TITLE
Browser analysis is obsolete

### ISSUE THREAD

**Issue by fred-wang** [othree/jquery.rtl-scroll-type#5]
This is the result in the latest updates:

* Gecko (Firefox) and WebKit (Safari) uses the "negative" type.
* Blink (Chrome, Opera, Edge) uses the "default" but will follow the CSSOM spec and switch to "negative" soon. See https://www.chromestatus.com/feature/5759578031521792
* Trident (Internet Explorer) probably still uses reverse (not tested).

**Comment by fred-wang** [comment]
@othree Thanks for the quick replies and for the follow-up changes ! Please let me know when the nex version library is released.

**Comment by othree** [comment]
2.0 is released last week
